[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 16
padding.y = 16
decorations = "Buttonless"
opacity = 0.98

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
